---
abstract: 'Flexible SDK supporting all eBay web services'
author:
  - 'Tim Keefer <tkeefer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: eBay-API-Simple
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Headers: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  URI: 1.57
  URI::Escape: 0
  XML::LibXML: 0
  XML::Parser: 0
  XML::Simple: 0
  YAML: 0
version: 0.29
