# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         eBay-API-Simple
version:      0.05
version_from: lib/eBay/API/SimpleBase.pm
installdirs:  site
requires:
    HTTP::Headers:                 0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    XML::LibXML:                   0
    XML::Parser:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
