--- #YAML:1.0
name:               eBay-API-Simple
version:            0.15
abstract:           Flexible SDK supporting all eBay web services
author:
    - Tim Keefer <tkeefer@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Headers:   0
    HTTP::Request:   0
    LWP::UserAgent:  0
    URI::Escape:     0
    XML::LibXML:     0
    XML::Parser:     0
    XML::Simple:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
